name: .NET

on:
  push:
    branches: [ "master" ]
    paths:
      - src/*

# TODO: Currently all jobs will create a different releases with the same name
# For Example:
# 1. Release 5 (for linux x64)
# 2. Release 5 (for windows x64)
# This needs to be fixed. Only one release should be created at the pipeline run, and that release should include all artifacts (windows, linux, etc)
jobs:
  docker-build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t mtokarevv/webhookshell:latest --push .

  framework-specific:
    name: Build and Release Framework-Dependent Package
    uses: ./.github/workflows/dotnet.yml
    with:
      release-name: Release ${{ github.run_number }} (Required .net6.0 runtime)
      version-tag: ${{ github.run_number }}

  linux-x64:
    name: Build and Release for linux x64
    uses: ./.github/workflows/dotnet.yml
    with:
      release-name: Release ${{ github.run_number }} for Linux
      runtime-name: linux-x64
      runtime-configuration: --runtime linux-x64
      version-tag: ${{ github.run_number }}

  rhel-x64:
    name: Build and Release for RHEL x64
    uses: ./.github/workflows/dotnet.yml
    with:
      release-name: Release ${{ github.run_number }} for RedHat
      runtime-name: rhel-x64
      runtime-configuration: --runtime rhel-x64
      version-tag: ${{ github.run_number }}

  windows-x64:
    name: Build and Release for Windows x64
    uses: ./.github/workflows/dotnet.yml
    with:
      release-name: Release ${{ github.run_number }} for Windows
      runtime-name: win-x64
      runtime-configuration: --runtime win-x64
      version-tag: ${{ github.run_number }}
